apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yr5xlewle-go
  janus-idp.io/tekton: yr5xlewle-go
  backstage.io/kubernetes-id: yr5xlewle-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yr5xlewle-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
