apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yr5xlewle-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yr5xlewle-go 
  name: yr5xlewle-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yr5xlewle-go 
