apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: yr5xlewle-go-gitops
  description: This is GitOps manifest for yr5xlewle-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=yr5xlewle-go
    backstage.io/kubernetes-id: yr5xlewle-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: yr5xlewle-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:yr5xlewle-go
